import Link from 'next/link'
import PolicyPageShell from '@/components/layout/PolicyPageShell'

export default function DisclaimerPage() {
  return (
    <PolicyPageShell>
      <article>
        <header className="border-b border-white/10 pb-8 text-center">
          <h1 className="font-display text-[clamp(20px,3.2vw,28px)] font-normal uppercase tracking-[0.06em] text-white">
            Disclaimer
          </h1>
          <p className="mt-4 text-sm font-medium text-mml-teal">Operated by Qismat Ventures W.L.L</p>
          <p className="mt-6 text-[13px] leading-relaxed text-white">
            <span className="block">Effective Date: [To be set]</span>
            <span className="mt-1 block">Last Updated: [To be set]</span>
          </p>
        </header>

        <div className="mt-10 space-y-8 text-[14px] leading-relaxed text-white sm:text-[15px]">
          <p>
            This Disclaimer governs your access to and use of Make My Lesson across all platforms operated by Qismat
            Ventures W.L.L, including the website, mobile applications, and any associated services.
          </p>
          <p>By using Make My Lesson, you acknowledge and accept the terms set out below.</p>
          <p>
            This Disclaimer forms part of and should be read alongside the Make My Lesson{' '}
            <Link href="/terms-of-service" className="text-mml-teal underline-offset-2 hover:underline">
              Terms of Service
            </Link>
            ,{' '}
            <Link href="/privacy-policy" className="text-mml-teal underline-offset-2 hover:underline">
              Privacy Policy
            </Link>
            ,{' '}
            <Link href="/acceptable-use-policy" className="text-mml-teal underline-offset-2 hover:underline">
              Acceptable Use Policy
            </Link>
            , and{' '}
            <Link href="/cookie-policy" className="text-mml-teal underline-offset-2 hover:underline">
              Cookie Policy
            </Link>
            .
          </p>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">1. General Platform Disclaimer</h2>
            <p className="mb-3">
              Make My Lesson is an educational technology platform designed to assist teachers in planning lessons and
              creating teaching materials.
            </p>
            <p className="mb-3">It is not intended to replace:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Professional teaching judgment</li>
              <li>Institutional or school policies</li>
              <li>Curriculum requirements or standards</li>
              <li>Official examination boards or assessment authorities</li>
            </ul>
            <p className="mb-3">
              All materials generated by Make My Lesson — including lesson plans, presentations, classroom activities, and
              assessments — are provided for educational assistance only.
            </p>
            <p className="mb-3">They are not:</p>
            <ul className="list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Official curriculum documents</li>
              <li>Certified teaching materials</li>
              <li>Guaranteed to be accurate, complete, or up to date</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">2. AI-Generated Content Disclaimer</h2>
            <p className="mb-3">Make My Lesson uses artificial intelligence to generate educational content.</p>
            <p className="mb-3">You acknowledge that:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>AI-generated content may contain errors, inaccuracies, or omissions</li>
              <li>Content may not fully align with specific curricula or exam board requirements</li>
              <li>Outputs are generated based on input data and may vary in quality or completeness</li>
            </ul>
            <p className="mb-3">You are solely responsible for:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Reviewing all generated content</li>
              <li>Editing and validating materials before classroom use</li>
              <li>Ensuring alignment with curriculum, standards, and institutional requirements</li>
            </ul>
            <p>Make My Lesson does not guarantee the accuracy or reliability of AI-generated content.</p>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">3. Assessment &amp; Evaluation Disclaimer (Critical)</h2>
            <p className="mb-3">Where Make My Lesson is used to generate:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Tests</li>
              <li>Quizzes</li>
              <li>Assessments</li>
              <li>Mark schemes</li>
            </ul>
            <p className="mb-3">You acknowledge that:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>These materials are assistive drafts only</li>
              <li>They must be reviewed and approved before use in any formal or informal assessment</li>
              <li>They are not validated against official exam board standards</li>
            </ul>
            <p className="mb-3">Make My Lesson is not responsible for:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Assessment accuracy</li>
              <li>Grading decisions</li>
              <li>Student outcomes</li>
              <li>Misalignment with curriculum or standards</li>
            </ul>
            <p>All responsibility remains with the teacher or institution.</p>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">4. No Guarantee of Educational or Teaching Outcomes</h2>
            <p className="mb-3">
              Make My Lesson makes no representations or warranties that use of the platform will result in:
            </p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Improved teaching performance</li>
              <li>Better student outcomes</li>
              <li>Curriculum compliance</li>
              <li>Assessment validity</li>
            </ul>
            <p>Outcomes depend on individual use, professional judgment, and external factors beyond our control.</p>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">5. Platform Availability</h2>
            <p className="mb-3">Make My Lesson is provided on an &quot;as is&quot; and &quot;as available&quot; basis.</p>
            <p className="mb-3">We do not guarantee:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Continuous or uninterrupted access</li>
              <li>Absence of technical issues or errors</li>
              <li>Availability of specific features</li>
            </ul>
            <p>Temporary interruptions or updates may occur without notice.</p>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">6. Third-Party Services</h2>
            <p className="mb-3">Make My Lesson may integrate with third-party services, including:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Google Firebase (data storage, authentication, analytics)</li>
              <li>Google Classroom and Microsoft Teams (exports)</li>
              <li>Payment providers (e.g., Paddle, Apple, Google)</li>
            </ul>
            <p className="mb-3">We do not control or assume responsibility for:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Third-party services</li>
              <li>Their content, availability, or policies</li>
            </ul>
            <p>Use of third-party services is subject to their own terms.</p>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">7. Intellectual Property</h2>
            <p className="mb-3">
              All platform content, design, and technology are owned by or licensed to Qismat Ventures W.L.L.
            </p>
            <p className="mb-3">Users may not:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Copy or redistribute platform materials</li>
              <li>Reverse engineer or exploit the system</li>
              <li>Use branding without permission</li>
            </ul>
            <p>User-generated content remains the property of the user, but may be processed for platform functionality.</p>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">8. Limitation of Liability</h2>
            <p className="mb-3">To the fullest extent permitted by law, Qismat Ventures W.L.L shall not be liable for:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Any indirect, incidental, or consequential damages</li>
              <li>Errors in AI-generated content</li>
              <li>Decisions made based on generated materials</li>
              <li>Classroom or institutional outcomes</li>
              <li>Loss of data or teaching materials</li>
            </ul>
            <p className="mb-3">Total liability shall not exceed:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>The amount paid by you in the preceding 12 months, or</li>
              <li>USD 100 (whichever is greater)</li>
            </ul>
            <p>Nothing in this Disclaimer limits liability where prohibited by law.</p>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">9. No Professional Advice</h2>
            <p className="mb-3">Nothing generated by Make My Lesson constitutes:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Professional educational advice</li>
              <li>Official curriculum guidance</li>
              <li>Legal, financial, or institutional advice</li>
            </ul>
            <p>All content is for general educational assistance only.</p>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">10. Institutional Responsibility</h2>
            <p className="mb-3">Schools and institutions using Make My Lesson are responsible for:</p>
            <ul className="mb-4 list-disc space-y-2 pl-5 marker:text-mml-teal">
              <li>Ensuring proper use by staff</li>
              <li>Reviewing generated materials</li>
              <li>Maintaining compliance with educational standards</li>
              <li>Supervising how materials are used in classrooms</li>
            </ul>
            <p>Make My Lesson does not assume responsibility for institutional implementation.</p>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">11. Governing Law</h2>
            <p>This Disclaimer is governed by the laws of the Kingdom of Bahrain.</p>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">12. Changes to This Disclaimer</h2>
            <p className="mb-3">We may update this Disclaimer periodically.</p>
            <p>Continued use of the platform constitutes acceptance of updates.</p>
          </section>

          <section>
            <h2 className="mb-3 font-display text-lg font-normal text-white">13. Contact</h2>
            <p className="mb-3">For questions regarding this Disclaimer:</p>
            <ul className="list-none space-y-1">
              <li>
                <a href="mailto:hello@makemylesson.ai" className="text-mml-teal underline-offset-2 hover:underline">
                  hello@makemylesson.ai
                </a>
              </li>
              <li>
                <a href="mailto:support@makemylesson.ai" className="text-mml-teal underline-offset-2 hover:underline">
                  support@makemylesson.ai
                </a>
              </li>
            </ul>
            <p className="mt-6 text-sm text-white">
              Operated by Qismat Ventures W.L.L
              <br />
              Office 501, Building 1025, Road 3621, Block 436, Al-Seef, Kingdom of Bahrain
            </p>
          </section>
        </div>
      </article>
    </PolicyPageShell>
  )
}
